FIND_PATH(OST_INCLUDE_DIR indimodule.h)
SET(OST_NAMES ${OST_NAMES} libostindimodule.so libostbasemodule.so)
FIND_LIBRARY(OST_LIBRARY_BASE NAMES ${OST_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set OST_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OST DEFAULT_MSG OST_INCLUDE_DIR OST_LIBRARY_BASE)

IF(OST_FOUND)
  SET(OST_LIBRARIES ${OST_LIBRARY_BASE})
ELSE(OST_FOUND)
  MESSAGE(FATAL_ERROR "OST is not found. Please install it first.")	
ENDIF(OST_FOUND)
